services:
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./temp:/app/temp
      - ./database:/app/database   # если тут sqlite-файлы, чтобы не терялись при пересборке
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data: